# Databricks notebook source
# MAGIC %md
# MAGIC #00. Introduction
# MAGIC The key functionalities integrated into this notebook include:
# MAGIC
# MAGIC 1. **Importing the RAG Pipeline**:
# MAGIC    - The RAG pipeline is imported to handle the entire process of retrieving and generating responses to user queries. This pipeline integrates various components to ensure efficient and accurate information retrieval and response generation.
# MAGIC
# MAGIC 2. **Registering the Model in Databricks Unity Catalog**:
# MAGIC    - The trained RAG model is registered in Databricks Unity Catalog. This step involves storing the model in a centralized and managed repository, enabling easy access and governance of the model.
# MAGIC
# MAGIC 3. **Updating the Champion Alias to the Latest Model**:
# MAGIC    - The champion alias, which represents the current best version of the model, is updated to point to the latest registered model. This ensures that all references to the champion alias use the most recent and accurate version of the model.
# MAGIC
# MAGIC 4. **Updating the Serving Endpoint with the Latest Model**:
# MAGIC    - The serving endpoint, responsible for handling incoming requests and serving model predictions, is updated to utilize the latest version of the RAG model. This guarantees that users receive responses generated by the most up-to-date and high-performing model.
# MAGIC
# MAGIC Overall, this notebook facilitates the seamless integration, registration, and deployment of the RAG pipeline in Databricks Unity Catalog, ensuring that the latest and best-performing model is always in use.

# COMMAND ----------

# MAGIC %md
# MAGIC #01. Import Libraries and Notebooks

# COMMAND ----------

# MAGIC %run ./RAG_PIPELINE

# COMMAND ----------

import mlflow
from mlflow import MlflowClient
from mlflow.deployments import get_deploy_client

# COMMAND ----------

# MAGIC %md
# MAGIC #02. Setting up configs for Notebook
# MAGIC

# COMMAND ----------

dbcEnv = os.getenv("dbc_environment")

# COMMAND ----------

serving_config = {
    "model_name": "question-answering",
    "catalog_settings": {"catalog": f"commercial_{dbcEnv}", "schema": "medical_affair_core"},
    "serving_endpoint_settings": {
        "endpoint_name": "question-answer",
        "workload_size": "Small",
        "scale_to_zero_enabled": True,
    },
}

# COMMAND ----------

mlflow.set_registry_uri("databricks-uc")

# COMMAND ----------

client = MlflowClient()

# COMMAND ----------

# MAGIC %md
# MAGIC #03. Register Model to Catalog

# COMMAND ----------

registry_details = mlflow.register_model(
    model_uri=f"runs:/{run_id}/{serving_config['model_name']}",
    name=f"{serving_config['catalog_settings']['catalog']}.{serving_config['catalog_settings']['schema']}.{serving_config['model_name']}"
)

# COMMAND ----------

# Set the model version alias to "Champion"
client.set_registered_model_alias(
    name=registry_details.name,
    version=registry_details.version,
    alias="Champion"
)

# COMMAND ----------

# MAGIC %md
# MAGIC #04. Update Serving Endpoint

# COMMAND ----------

client = get_deploy_client("databricks")

    # Update the serving endpoint configuration
try:
    endpoint = client.update_endpoint(
        endpoint=serving_config["serving_endpoint_settings"]["endpoint_name"],
        config={
            "served_entities": [
                {
                    "entity_name": registry_details.name,
                    "entity_version": registry_details.version,
                    "workload_size": serving_config["serving_endpoint_settings"][
                        "workload_size"
                    ],
                    "scale_to_zero_enabled": serving_config["serving_endpoint_settings"][
                        "scale_to_zero_enabled"
                    ],
                }
            ],
            "traffic_config": {
                "routes": [
                    {
                        "served_model_name": f"{serving_config['model_name']}-{registry_details.version}",
                        "traffic_percentage": 100,
                    }
                ]
            },
        },
    )
except Exception as e:
    if 'RESOURCE_DOES_NOT_EXIST' in str(e):
        logging.warning('Endpoint did not exist. will be created')
        endpoint = client.create_endpoint(
        name=serving_config["serving_endpoint_settings"]["endpoint_name"],
        config={
            "served_entities": [
                {
                    "entity_name": registry_details.name,
                    "entity_version": registry_details.version,
                    "workload_size": serving_config["serving_endpoint_settings"][
                        "workload_size"
                    ],
                    "scale_to_zero_enabled": serving_config["serving_endpoint_settings"][
                        "scale_to_zero_enabled"
                    ],
                }
            ],
            "traffic_config": {
                "routes": [
                    {
                        "served_model_name": f"{serving_config['model_name']}-{registry_details.version}",
                        "traffic_percentage": 100,
                    }
                ]
            },
        },
    )
